/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/myHolo.gltf');
	const { actions } = useAnimations(animations, group);

	
	return (
		<group ref={group} {...props} dispose={null}>
			<group
				name='Scene'
				userData={{
					rsl_hide_mesh_during_play: 0,
					rsl_reset_scene_on_stop: 1,
					rsl_retargeting_armature_source: {
						name: 'Object_341.002',
						type: 'Object',
					},
					rsl_retargeting_armature_target: {
						name: 'Armature.003',
						type: 'Object',
					},
					rsl_retargeting_bone_list: [
						{
							bone_name_key: 'hip',
							bone_name_source: '_rootJoint',
							bone_name_target: 'mixamorig:Hips',
						},
						{
							bone_name_key: 'neck',
							bone_name_source: 'Chest_M_0260',
							bone_name_target: 'mixamorig:Neck',
						},
						{
							bone_name_key: 'custom_bone_mixamorig:spine1',
							bone_name_source: 'Neck_M_0271',
							bone_name_target: 'mixamorig:Spine1',
						},
						{
							bone_name_key: 'custom_bone_mixamorig:spine',
							bone_name_source: 'Head_M_0272',
							bone_name_target: 'mixamorig:Spine',
						},
						{
							bone_name_key: 'head',
							bone_name_source: 'HeadEnd_M_0273',
							bone_name_target: 'mixamorig:Head',
						},
						{
							bone_name_key: 'rightShoulder',
							bone_name_source: 'Scapula_R_0286',
							bone_name_target: 'mixamorig:RightShoulder',
						},
						{
							bone_name_key: 'rightUpperArm',
							bone_name_source: 'Shoulder_R_0267',
							bone_name_target: 'mixamorig:RightShoulder',
						},
						{
							bone_name_key: 'rightLowerArm',
							bone_name_source: 'Elbow_R_0287',
							bone_name_target: 'mixamorig:RightForeArm',
						},
						{
							bone_name_key: 'rightHand',
							bone_name_source: 'Wrist_R_0288',
							bone_name_target: '',
						},
						{
							bone_name_key: 'leftShoulder',
							bone_name_source: 'Scapula_L_0289',
							bone_name_target: 'mixamorig:LeftShoulder',
						},
						{
							bone_name_key: 'leftUpperArm',
							bone_name_source: 'Shoulder_L_0290',
							bone_name_target: 'mixamorig:LeftShoulder',
						},
						{
							bone_name_key: 'leftLowerArm',
							bone_name_source: 'Elbow_L_0291',
							bone_name_target: 'mixamorig:LeftForeArm',
						},
						{
							bone_name_key: 'leftHand',
							bone_name_source: 'Wrist_L_0292',
							bone_name_target: 'mixamorig:LeftHand',
						},
						{
							bone_name_key: 'rightUpLeg',
							bone_name_source: 'Hip_R_0296',
							bone_name_target: 'mixamorig:RightUpLeg',
						},
						{
							bone_name_key: 'rightLeg',
							bone_name_source: 'Ankle_R_0297_scaleCompensation',
							bone_name_target: 'mixamorig:RightLeg',
						},
						{
							bone_name_key: 'rightFoot',
							bone_name_source: 'Ankle_R_0297',
							bone_name_target: 'mixamorig:RightFoot',
						},
						{
							bone_name_key: 'rightToe',
							bone_name_source: 'Toes_R_0298',
							bone_name_target: 'mixamorig:RightToeBase',
						},
						{
							bone_name_key: 'leftUpLeg',
							bone_name_source: 'Hip_L_0299',
							bone_name_target: 'mixamorig:LeftUpLeg',
						},
						{
							bone_name_key: 'leftLeg',
							bone_name_source: 'Ankle_L_0300_scaleCompensation',
							bone_name_target: 'mixamorig:LeftLeg',
						},
						{
							bone_name_key: 'leftFoot',
							bone_name_source: 'Ankle_L_0300',
							bone_name_target: '',
						},
						{
							bone_name_key: 'leftToe',
							bone_name_source: 'Toes_L_0301',
							bone_name_target: 'mixamorig:LeftFoot',
						},
					],
					rsl_retargeting_bone_list_index: 18,
					rsl_retargeting_use_pose: 1,
					rsl_retargeting_auto_scaling: 1,
				}}>
				<group
					name='Sketchfab_model'
					position={[-0.642, 0.562, 9.161]}
					rotation={[-Math.PI / 2, 0, -0.021]}
					scale={2.11}
					userData={{ name: 'Sketchfab_model' }}>
					<group
						name='b24b11e4ba2d4752b58f0b5813062b99fbx'
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.01}
						userData={{ name: 'b24b11e4ba2d4752b58f0b5813062b99.fbx' }}>
						<group name='Object_2' userData={{ name: 'Object_2' }}>
							<group name='RootNode' userData={{ name: 'RootNode' }}>
								<group
									name='BlendShapes_1'
									position={[73.876, 0, 0]}
									userData={{ name: 'BlendShapes_1' }}
								/>
								<group name='Group' userData={{ name: 'Group' }}>
									<group
										name='DeformationSystem'
										userData={{ name: 'DeformationSystem' }}>
										<group
											name='Object_383'
											position={[-8.065, -15.685, -4.141]}
											userData={{ name: 'Object_383' }}
										/>
										<group
											name='Object_384'
											position={[-8.065, -15.685, -4.141]}
											userData={{ name: 'Object_384' }}
										/>
										<group
											name='Object_385'
											position={[-8.065, -15.685, -4.141]}
											userData={{ name: 'Object_385' }}
										/>
										<group
											name='Object_386'
											position={[-8.065, -15.685, -4.141]}
											userData={{ name: 'Object_386' }}
										/>
										<mesh
											name='1'
											castShadow
											receiveShadow
											geometry={nodes['1'].geometry}
											material={materials.blinn2}
											morphTargetDictionary={nodes['1'].morphTargetDictionary}
											morphTargetInfluences={nodes['1'].morphTargetInfluences}
											position={[-8.065, -15.685, -4.141]}
											userData={{ targetNames: ['target_0'], name: '1' }}
										/>
										<mesh
											name='2'
											castShadow
											receiveShadow
											geometry={nodes['2'].geometry}
											material={materials.pasted__blinn1}
											morphTargetDictionary={nodes['2'].morphTargetDictionary}
											morphTargetInfluences={nodes['2'].morphTargetInfluences}
											position={[-8.065, -15.685, -4.141]}
											userData={{ targetNames: ['target_0'], name: '2' }}
										/>
										<mesh
											name='0'
											castShadow
											receiveShadow
											geometry={nodes['0'].geometry}
											material={materials.lambert1}
											morphTargetDictionary={nodes['0'].morphTargetDictionary}
											morphTargetInfluences={nodes['0'].morphTargetInfluences}
											position={[-8.065, -15.685, -4.141]}
											userData={{ targetNames: ['target_0'], name: '0' }}
										/>
									</group>
									<group
										name='FitSkeleton'
										userData={{ name: 'FitSkeleton' }}
									/>
									<group name='Geometry' userData={{ name: 'Geometry' }} />
									<group
										name='MotionSystem'
										userData={{ name: 'MotionSystem' }}
									/>
								</group>
								<group
									name='persp1'
									position={[1.188, 26.401, 111.438]}
									rotation={[0, 1.56, 0.026]}
									userData={{ name: 'persp1' }}
								/>
							</group>
						</group>
					</group>
				</group>
				<group
					name='Armature001'
					position={[-1.623, 0.125, 8.832]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.021}
					userData={{ name: 'Armature.001' }}
				/>
				<group
					name='Sketchfab_model001'
					position={[-0.642, 0.562, 9.161]}
					rotation={[-Math.PI / 2, 0, -0.021]}
					scale={2.11}
					userData={{ name: 'Sketchfab_model.001' }}
				/>
				<group
					name='Object_341002'
					position={[-0.73, 0.884, -7.478]}
					scale={0.155}
					userData={{ name: 'Object_341.002' }}>
					<primitive object={nodes._rootJoint} />
					<primitive object={nodes.mixamorigHips} />
				</group>
				<group name='Object_341003' userData={{ name: 'Object_341.003' }}>
					<primitive object={nodes._rootJoint_1} />
				</group>
				<mesh
					name='Line175'
					castShadow
					receiveShadow
					geometry={nodes.Line175.geometry}
					material={materials['Material #8368.001']}
					position={[8.221, 0.12, 1.352]}
					scale={16.371}
					userData={{ name: 'Line175', MaxHandle: 638 }}
				/>
				<group
					name='Object157'
					position={[3.905, 0.12, -3.072]}
					scale={16.371}
					userData={{ name: 'Object157', MaxHandle: 639 }}>
					<mesh
						name='Mesh045'
						castShadow
						receiveShadow
						geometry={nodes.Mesh045.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh045_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh045_1.geometry}
						material={materials['Material #7673.001']}
					/>
				</group>
				<group
					name='Box093'
					position={[-0.186, 3.556, -5.911]}
					scale={16.371}
					userData={{
						name: 'Box093',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 641,
					}}>
					<mesh
						name='Mesh047'
						castShadow
						receiveShadow
						geometry={nodes.Mesh047.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh047_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh047_1.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh047_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh047_2.geometry}
						material={materials['Material #6383.001']}
					/>
					<mesh
						name='Mesh047_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh047_3.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh047_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh047_4.geometry}
						material={materials['Material #2279.001']}
					/>
				</group>
				<mesh
					name='Line210'
					castShadow
					receiveShadow
					geometry={nodes.Line210.geometry}
					material={materials['Material #6590.001']}
					position={[-4.34, 0.989, 8.877]}
					scale={16.371}
					userData={{ name: 'Line210', MaxHandle: 643 }}
				/>
				<group
					name='Double_Stairs'
					position={[-2.662, 1.4, 1.54]}
					scale={16.371}
					userData={{
						name: 'Double Stairs',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 645,
					}}>
					<mesh
						name='Mesh051'
						castShadow
						receiveShadow
						geometry={nodes.Mesh051.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh051_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh051_1.geometry}
						material={materials['Material #6680.001']}
					/>
				</group>
				<mesh
					name='Line212'
					castShadow
					receiveShadow
					geometry={nodes.Line212.geometry}
					material={materials['Material #8368.001']}
					position={[-0.48, 0.642, 5.825]}
					scale={16.371}
					userData={{ name: 'Line212', MaxHandle: 646 }}
				/>
				<mesh
					name='Sphere162'
					castShadow
					receiveShadow
					geometry={nodes.Sphere162.geometry}
					material={materials['Material #9277.001']}
					position={[2.566, 0.698, 1.173]}
					scale={16.371}
					userData={{
						name: 'Sphere162',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 649,
					}}
				/>
				<mesh
					name='Sphere183'
					castShadow
					receiveShadow
					geometry={nodes.Sphere183.geometry}
					material={materials['Material #9277.001']}
					position={[-2.089, 0.736, 6.038]}
					scale={16.371}
					userData={{
						name: 'Sphere183',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 650,
					}}
				/>
				<mesh
					name='Object179'
					castShadow
					receiveShadow
					geometry={nodes.Object179.geometry}
					material={materials['01 - Default.001']}
					position={[5.514, 0.873, -0.07]}
					scale={16.371}
					userData={{
						name: 'Object179',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 651,
					}}
				/>
				<group
					name='Cylinder268'
					position={[9.107, 0.339, 4.307]}
					scale={16.371}
					userData={{
						name: 'Cylinder268',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 652,
					}}>
					<mesh
						name='Mesh058'
						castShadow
						receiveShadow
						geometry={nodes.Mesh058.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh058_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh058_1.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh058_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh058_2.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh058_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh058_3.geometry}
						material={materials['Material #563.001']}
					/>
				</group>
				<mesh
					name='Line235'
					castShadow
					receiveShadow
					geometry={nodes.Line235.geometry}
					material={materials['Standardmaterial.001']}
					position={[5.146, 0.987, 2.781]}
					scale={16.371}
					userData={{
						name: 'Line235',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 653,
					}}
				/>
				<group
					name='Object185'
					position={[7.423, 0.341, 8.137]}
					scale={16.371}
					userData={{
						name: 'Object185',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 657,
					}}>
					<mesh
						name='Mesh063'
						castShadow
						receiveShadow
						geometry={nodes.Mesh063.geometry}
						material={materials['Material #20167.001']}
					/>
					<mesh
						name='Mesh063_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh063_1.geometry}
						material={materials['Material #8756.001']}
					/>
					<mesh
						name='Mesh063_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh063_2.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh063_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh063_3.geometry}
						material={materials['Material #6680.001']}
					/>
					<mesh
						name='Mesh063_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh063_4.geometry}
						material={materials['Material #21266.001']}
					/>
					<mesh
						name='Mesh063_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh063_5.geometry}
						material={materials['Material #23442.001']}
					/>
				</group>
				<group
					name='Box091'
					position={[5.107, 1.884, -2.307]}
					scale={16.371}
					userData={{
						name: 'Box091',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 659,
					}}>
					<mesh
						name='Mesh065'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh065_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_1.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh065_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_2.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh065_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_3.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh065_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_4.geometry}
						material={materials['Material #621.001']}
					/>
					<mesh
						name='Mesh065_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_5.geometry}
						material={materials['Material #23584.001']}
					/>
					<mesh
						name='Mesh065_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_6.geometry}
						material={materials['Material #6421.001']}
					/>
					<mesh
						name='Mesh065_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_7.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh065_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_8.geometry}
						material={materials['MultiMat_14 Slot #10.001']}
					/>
					<mesh
						name='Mesh065_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_9.geometry}
						material={materials['MultiMat_14 Slot #26.001']}
					/>
					<mesh
						name='Mesh065_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh065_10.geometry}
						material={materials['MultiMat_14 Slot #42.001']}
					/>
				</group>
				<group
					name='Cylinder272'
					position={[0.965, 0.45, 2.151]}
					scale={16.371}
					userData={{
						name: 'Cylinder272',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 660,
					}}>
					<mesh
						name='Mesh066'
						castShadow
						receiveShadow
						geometry={nodes.Mesh066.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh066_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh066_1.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh066_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh066_2.geometry}
						material={materials['Material #621.001']}
					/>
				</group>
				<group
					name='Cars'
					position={[-0.496, 3.004, -10.7]}
					scale={16.371}
					userData={{
						name: 'Cars',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 665,
					}}>
					<mesh
						name='Mesh071'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071.geometry}
						material={materials['Material #6117.001']}
					/>
					<mesh
						name='Mesh071_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_1.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh071_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_2.geometry}
						material={materials['Material #7671.001']}
					/>
					<mesh
						name='Mesh071_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_3.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh071_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_4.geometry}
						material={materials['MultiMat_20 Slot #7.001']}
					/>
					<mesh
						name='Mesh071_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_5.geometry}
						material={materials['MultiMat_20 Slot #14.001']}
					/>
					<mesh
						name='Mesh071_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_6.geometry}
						material={materials['MultiMat_20 Slot #15.001']}
					/>
					<mesh
						name='Mesh071_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_7.geometry}
						material={materials['MultiMat_20 Slot #20.001']}
					/>
					<mesh
						name='Mesh071_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_8.geometry}
						material={materials['Material #8759.001']}
					/>
					<mesh
						name='Mesh071_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_9.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh071_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_10.geometry}
						material={materials['MultiMat_20 Slot #26.001']}
					/>
					<mesh
						name='Mesh071_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_11.geometry}
						material={materials['MultiMat_20 Slot #27.001']}
					/>
					<mesh
						name='Mesh071_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_12.geometry}
						material={materials['MultiMat_20 Slot #28.001']}
					/>
					<mesh
						name='Mesh071_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_13.geometry}
						material={materials['MultiMat_20 Slot #30.001']}
					/>
					<mesh
						name='Mesh071_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_14.geometry}
						material={materials['MultiMat_20 Slot #31.001']}
					/>
					<mesh
						name='Mesh071_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_15.geometry}
						material={materials['MultiMat_20 Slot #32.001']}
					/>
					<mesh
						name='Mesh071_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_16.geometry}
						material={materials['MultiMat_20 Slot #33.001']}
					/>
					<mesh
						name='Mesh071_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_17.geometry}
						material={materials['MultiMat_20 Slot #34.001']}
					/>
					<mesh
						name='Mesh071_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_18.geometry}
						material={materials['MultiMat_20 Slot #52.001']}
					/>
					<mesh
						name='Mesh071_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_19.geometry}
						material={materials['MultiMat_20 Slot #58.001']}
					/>
					<mesh
						name='Mesh071_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_20.geometry}
						material={materials['MultiMat_20 Slot #59.001']}
					/>
					<mesh
						name='Mesh071_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_21.geometry}
						material={materials['MultiMat_20 Slot #60.001']}
					/>
					<mesh
						name='Mesh071_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_22.geometry}
						material={materials['MultiMat_20 Slot #61.001']}
					/>
					<mesh
						name='Mesh071_23'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_23.geometry}
						material={materials['MultiMat_20 Slot #62.001']}
					/>
					<mesh
						name='Mesh071_24'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_24.geometry}
						material={materials['MultiMat_20 Slot #84.001']}
					/>
					<mesh
						name='Mesh071_25'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_25.geometry}
						material={materials['MultiMat_20 Slot #88.001']}
					/>
					<mesh
						name='Mesh071_26'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_26.geometry}
						material={materials['MultiMat_20 Slot #115.001']}
					/>
					<mesh
						name='Mesh071_27'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_27.geometry}
						material={materials['MultiMat_20 Slot #116.001']}
					/>
					<mesh
						name='Mesh071_28'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_28.geometry}
						material={materials['MultiMat_20 Slot #117.001']}
					/>
					<mesh
						name='Mesh071_29'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_29.geometry}
						material={materials['MultiMat_20 Slot #118.001']}
					/>
					<mesh
						name='Mesh071_30'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_30.geometry}
						material={materials['MultiMat_20 Slot #119.001']}
					/>
					<mesh
						name='Mesh071_31'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_31.geometry}
						material={materials['MultiMat_20 Slot #120.001']}
					/>
					<mesh
						name='Mesh071_32'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_32.geometry}
						material={materials['MultiMat_20 Slot #121.001']}
					/>
					<mesh
						name='Mesh071_33'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_33.geometry}
						material={materials['MultiMat_20 Slot #122.001']}
					/>
					<mesh
						name='Mesh071_34'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_34.geometry}
						material={materials['MultiMat_20 Slot #123.001']}
					/>
					<mesh
						name='Mesh071_35'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_35.geometry}
						material={materials['MultiMat_20 Slot #124.001']}
					/>
					<mesh
						name='Mesh071_36'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_36.geometry}
						material={materials['MultiMat_20 Slot #125.001']}
					/>
					<mesh
						name='Mesh071_37'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_37.geometry}
						material={materials['MultiMat_20 Slot #126.001']}
					/>
					<mesh
						name='Mesh071_38'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_38.geometry}
						material={materials['MultiMat_20 Slot #127.001']}
					/>
					<mesh
						name='Mesh071_39'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_39.geometry}
						material={materials['MultiMat_20 Slot #128.001']}
					/>
					<mesh
						name='Mesh071_40'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_40.geometry}
						material={materials['MultiMat_20 Slot #129.001']}
					/>
					<mesh
						name='Mesh071_41'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_41.geometry}
						material={materials['MultiMat_20 Slot #130.001']}
					/>
					<mesh
						name='Mesh071_42'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_42.geometry}
						material={materials['MultiMat_20 Slot #131.001']}
					/>
					<mesh
						name='Mesh071_43'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_43.geometry}
						material={materials['MultiMat_20 Slot #132.001']}
					/>
					<mesh
						name='Mesh071_44'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_44.geometry}
						material={materials['MultiMat_20 Slot #133.001']}
					/>
					<mesh
						name='Mesh071_45'
						castShadow
						receiveShadow
						geometry={nodes.Mesh071_45.geometry}
						material={materials['MultiMat_20 Slot #134.001']}
					/>
				</group>
				<group
					name='Object160'
					position={[-7.575, 1.176, 4.381]}
					scale={16.371}
					userData={{
						name: 'Object160',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 667,
					}}>
					<mesh
						name='Mesh073'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh073_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_1.geometry}
						material={materials['Material #2518.001']}
					/>
					<mesh
						name='Mesh073_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_2.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh073_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_3.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh073_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_4.geometry}
						material={materials['Material #6342.001']}
					/>
					<mesh
						name='Mesh073_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_5.geometry}
						material={materials['01 - Default.001']}
					/>
					<mesh
						name='Mesh073_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_6.geometry}
						material={materials['MultiMat_22 Slot #15.001']}
					/>
					<mesh
						name='Mesh073_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_7.geometry}
						material={materials['MultiMat_22 Slot #18.001']}
					/>
					<mesh
						name='Mesh073_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh073_8.geometry}
						material={materials['Material #10445.001']}
					/>
				</group>
				<group
					name='Object156'
					position={[-0.657, 0.12, -1.315]}
					scale={16.371}
					userData={{ name: 'Object156', MaxHandle: 668 }}>
					<mesh
						name='Mesh074'
						castShadow
						receiveShadow
						geometry={nodes.Mesh074.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh074_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh074_1.geometry}
						material={materials['Material #7673.001']}
					/>
				</group>
				<group
					name='Spheric_mountain'
					position={[-2.841, 0.101, -10.476]}
					scale={16.371}
					userData={{
						name: 'Spheric mountain',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 671,
					}}>
					<mesh
						name='Mesh077'
						castShadow
						receiveShadow
						geometry={nodes.Mesh077.geometry}
						material={materials['Material #20167.001']}
					/>
					<mesh
						name='Mesh077_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh077_1.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh077_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh077_2.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh077_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh077_3.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh077_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh077_4.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh077_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh077_5.geometry}
						material={materials['Material #6383.001']}
					/>
				</group>
				<mesh
					name='Object212'
					castShadow
					receiveShadow
					geometry={nodes.Object212.geometry}
					material={materials['Material #6342.001']}
					position={[-3.025, 4.257, -9.528]}
					scale={16.371}
					userData={{
						name: 'Object212',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 673,
					}}
				/>
				<mesh
					name='Object213'
					castShadow
					receiveShadow
					geometry={nodes.Object213.geometry}
					material={materials['Material #2279.001']}
					position={[-8.063, 3.151, -6.456]}
					scale={16.371}
					userData={{
						name: 'Object213',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 674,
					}}
				/>
				<group
					name='Object217'
					position={[-0.186, 3.556, -5.911]}
					scale={16.371}
					userData={{
						name: 'Object217',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 675,
					}}>
					<mesh
						name='Mesh081'
						castShadow
						receiveShadow
						geometry={nodes.Mesh081.geometry}
						material={materials['01 - Default.001']}
					/>
					<mesh
						name='Mesh081_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh081_1.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh081_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh081_2.geometry}
						material={materials['Material #17533.001']}
					/>
				</group>
				<group
					name='Object218'
					position={[5.146, 0.987, 2.781]}
					scale={16.371}
					userData={{
						name: 'Object218',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 676,
					}}>
					<mesh
						name='Mesh082'
						castShadow
						receiveShadow
						geometry={nodes.Mesh082.geometry}
						material={materials['MultiMat_31 Slot #2.001']}
					/>
					<mesh
						name='Mesh082_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh082_1.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh082_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh082_2.geometry}
						material={materials['Material #17533.001']}
					/>
				</group>
				<mesh
					name='Object219'
					castShadow
					receiveShadow
					geometry={nodes.Object219.geometry}
					material={materials['Material #17533.001']}
					position={[7.656, 1.011, -2.908]}
					scale={16.371}
					userData={{
						name: 'Object219',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 677,
					}}
				/>
				<group
					name='Box092'
					position={[7.666, 1.011, -2.897]}
					scale={16.371}
					userData={{
						name: 'Box092',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 636,
					}}>
					<mesh
						name='Mesh042'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042.geometry}
						material={materials['Material #14956.001']}
					/>
					<mesh
						name='Mesh042_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042_1.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh042_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042_2.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh042_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042_3.geometry}
						material={materials['Material #9307.001']}
					/>
					<mesh
						name='Mesh042_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042_4.geometry}
						material={materials['Material #8756.001']}
					/>
					<mesh
						name='Mesh042_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042_5.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh042_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh042_6.geometry}
						material={materials['Material #9279.001']}
					/>
				</group>
				<group
					name='Cone001'
					position={[-3.124, 1.4, -2.204]}
					scale={16.371}
					userData={{
						name: 'Cone001',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 640,
					}}>
					<mesh
						name='Mesh046'
						castShadow
						receiveShadow
						geometry={nodes.Mesh046.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh046_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh046_1.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh046_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh046_2.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh046_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh046_3.geometry}
						material={materials['Material #20620.001']}
					/>
				</group>
				<group
					name='Third_musoleum'
					position={[7.151, 0.692, 1.929]}
					scale={16.371}
					userData={{
						name: 'Third musoleum',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 654,
					}}>
					<mesh
						name='Mesh060'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060.geometry}
						material={materials['Material #8756.001']}
					/>
					<mesh
						name='Mesh060_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_1.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh060_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_2.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh060_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_3.geometry}
						material={materials['Material #9307.001']}
					/>
					<mesh
						name='Mesh060_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_4.geometry}
						material={materials['Material #332.001']}
					/>
					<mesh
						name='Mesh060_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_5.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh060_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_6.geometry}
						material={materials['Material #24544.001']}
					/>
					<mesh
						name='Mesh060_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh060_7.geometry}
						material={materials['Material #319.001']}
					/>
				</group>
				<mesh
					name='Plane003'
					castShadow
					receiveShadow
					geometry={nodes.Plane003.geometry}
					material={materials['Material #9131.001']}
					position={[2.182, 0.78, 0.858]}
					scale={16.371}
					userData={{
						name: 'Plane003',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 648,
					}}
				/>
				<group
					name='Boat_level'
					position={[7.431, 1.135, -3.568]}
					scale={16.371}
					userData={{
						name: 'Boat level',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 662,
					}}>
					<mesh
						name='Mesh068'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068.geometry}
						material={materials['Material #621.001']}
					/>
					<mesh
						name='Mesh068_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_1.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh068_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_2.geometry}
						material={materials['Material #8425.001']}
					/>
					<mesh
						name='Mesh068_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_3.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh068_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_4.geometry}
						material={materials['MultiMat_17 Slot #7.001']}
					/>
					<mesh
						name='Mesh068_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_5.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh068_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_6.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh068_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_7.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh068_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_8.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh068_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_9.geometry}
						material={materials['Material #19916.001']}
					/>
					<mesh
						name='Mesh068_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh068_10.geometry}
						material={materials['Material #560.001']}
					/>
				</group>
				<group
					name='Cylinder229'
					position={[-5.652, 0.807, 6.558]}
					scale={16.371}
					userData={{
						name: 'Cylinder229',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 664,
					}}>
					<mesh
						name='Mesh070'
						castShadow
						receiveShadow
						geometry={nodes.Mesh070.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh070_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh070_1.geometry}
						material={materials['Material #560.001']}
					/>
					<mesh
						name='Mesh070_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh070_2.geometry}
						material={materials['Material #2279.001']}
					/>
				</group>
				<group
					name='Line207'
					position={[3.386, 1.396, -1.484]}
					scale={16.371}
					userData={{
						name: 'Line207',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 642,
					}}>
					<mesh
						name='Mesh048'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048.geometry}
						material={materials['Material #21252.001']}
					/>
					<mesh
						name='Mesh048_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_1.geometry}
						material={materials['Material #8425.001']}
					/>
					<mesh
						name='Mesh048_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_2.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh048_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_3.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh048_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_4.geometry}
						material={materials['Material #23584.001']}
					/>
					<mesh
						name='Mesh048_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_5.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh048_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_6.geometry}
						material={materials['Material #6383.001']}
					/>
					<mesh
						name='Mesh048_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_7.geometry}
						material={materials['Material #6342.001']}
					/>
					<mesh
						name='Mesh048_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_8.geometry}
						material={materials['01 - Default.001']}
					/>
					<mesh
						name='Mesh048_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh048_9.geometry}
						material={materials['Material #9348.001']}
					/>
				</group>
				<mesh
					name='Line171'
					castShadow
					receiveShadow
					geometry={nodes.Line171.geometry}
					material={materials['Material #9171.001']}
					position={[1.673, 0.12, 9.225]}
					scale={16.371}
					userData={{
						name: 'Line171',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 637,
					}}
				/>
				<group
					name='Object183'
					position={[-5.095, 0.336, 11.096]}
					scale={16.371}
					userData={{
						name: 'Object183',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 666,
					}}>
					<mesh
						name='Mesh072'
						castShadow
						receiveShadow
						geometry={nodes.Mesh072.geometry}
						material={materials['Material #6680.001']}
					/>
					<mesh
						name='Mesh072_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh072_1.geometry}
						material={materials['Material #6117.001']}
					/>
					<mesh
						name='Mesh072_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh072_2.geometry}
						material={materials['Material #23584.001']}
					/>
					<mesh
						name='Mesh072_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh072_3.geometry}
						material={materials['Material #9334.001']}
					/>
				</group>
				<group
					name='Red_House_Level'
					position={[-1.397, 0.682, 5.98]}
					scale={16.371}
					userData={{
						name: 'Red House Level',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 647,
					}}>
					<mesh
						name='Mesh053'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053.geometry}
						material={materials['Material #6404.001']}
					/>
					<mesh
						name='Mesh053_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_1.geometry}
						material={materials['Material #8371.001']}
					/>
					<mesh
						name='Mesh053_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_2.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh053_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_3.geometry}
						material={materials['Material #8756.001']}
					/>
					<mesh
						name='Mesh053_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_4.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh053_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_5.geometry}
						material={materials['Material #8425.001']}
					/>
					<mesh
						name='Mesh053_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_6.geometry}
						material={materials['Material #8757.001']}
					/>
					<mesh
						name='Mesh053_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_7.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh053_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_8.geometry}
						material={materials['MultiMat_7 Slot #27.001']}
					/>
					<mesh
						name='Mesh053_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_9.geometry}
						material={materials['MultiMat_7 Slot #28.001']}
					/>
					<mesh
						name='Mesh053_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_10.geometry}
						material={materials['MultiMat_7 Slot #29.001']}
					/>
					<mesh
						name='Mesh053_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_11.geometry}
						material={materials['MultiMat_7 Slot #30.001']}
					/>
					<mesh
						name='Mesh053_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_12.geometry}
						material={materials['MultiMat_7 Slot #31.001']}
					/>
					<mesh
						name='Mesh053_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_13.geometry}
						material={materials['MultiMat_7 Slot #32.001']}
					/>
					<mesh
						name='Mesh053_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_14.geometry}
						material={materials['MultiMat_7 Slot #33.001']}
					/>
					<mesh
						name='Mesh053_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_15.geometry}
						material={materials['MultiMat_7 Slot #34.001']}
					/>
					<mesh
						name='Mesh053_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_16.geometry}
						material={materials['MultiMat_7 Slot #35.001']}
					/>
					<mesh
						name='Mesh053_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_17.geometry}
						material={materials['MultiMat_7 Slot #36.001']}
					/>
					<mesh
						name='Mesh053_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_18.geometry}
						material={materials['MultiMat_7 Slot #37.001']}
					/>
					<mesh
						name='Mesh053_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_19.geometry}
						material={materials['MultiMat_7 Slot #38.001']}
					/>
					<mesh
						name='Mesh053_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_20.geometry}
						material={materials['Material #9348.001']}
					/>
					<mesh
						name='Mesh053_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_21.geometry}
						material={materials['01 - Default.001']}
					/>
					<mesh
						name='Mesh053_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_22.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh053_23'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_23.geometry}
						material={materials['Material #560.001']}
					/>
					<mesh
						name='Mesh053_24'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_24.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh053_25'
						castShadow
						receiveShadow
						geometry={nodes.Mesh053_25.geometry}
						material={materials['Material #6383.001']}
					/>
				</group>
				<group
					name='Sphere185'
					position={[-3.202, 1.515, 0.501]}
					scale={16.371}
					userData={{
						name: 'Sphere185',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 644,
					}}>
					<mesh
						name='Mesh050'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh050_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_1.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh050_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_2.geometry}
						material={materials['Material #621.001']}
					/>
					<mesh
						name='Mesh050_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_3.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh050_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_4.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh050_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_5.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh050_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_6.geometry}
						material={materials['Material #14956.001']}
					/>
					<mesh
						name='Mesh050_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_7.geometry}
						material={materials['Material #6383.001']}
					/>
					<mesh
						name='Mesh050_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_8.geometry}
						material={materials['Material #6404.001']}
					/>
					<mesh
						name='Mesh050_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_9.geometry}
						material={materials['Material #23584.001']}
					/>
					<mesh
						name='Mesh050_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_10.geometry}
						material={materials['Material #7671.001']}
					/>
					<mesh
						name='Mesh050_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_11.geometry}
						material={materials['Material #7844.001']}
					/>
					<mesh
						name='Mesh050_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_12.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh050_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_13.geometry}
						material={materials['Material #7829.001']}
					/>
					<mesh
						name='Mesh050_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_14.geometry}
						material={materials['Material #7830.001']}
					/>
					<mesh
						name='Mesh050_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_15.geometry}
						material={materials['Material #6680.001']}
					/>
					<mesh
						name='Mesh050_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_16.geometry}
						material={materials['Material #7781.001']}
					/>
					<mesh
						name='Mesh050_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_17.geometry}
						material={materials['Material #7675.001']}
					/>
					<mesh
						name='Mesh050_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_18.geometry}
						material={materials['Material #7672.001']}
					/>
					<mesh
						name='Mesh050_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_19.geometry}
						material={materials['Material #7564.001']}
					/>
					<mesh
						name='Mesh050_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_20.geometry}
						material={materials['Material #6342.001']}
					/>
					<mesh
						name='Mesh050_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_21.geometry}
						material={materials['Material #7549.001']}
					/>
					<mesh
						name='Mesh050_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh050_22.geometry}
						material={materials['Material #8757.001']}
					/>
				</group>
				<group
					name='Sea_Stuff'
					position={[5.274, 1.3, 10.19]}
					scale={16.371}
					userData={{
						name: 'Sea Stuff',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 655,
					}}>
					<mesh
						name='Mesh061'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061.geometry}
						material={materials['Material #10570.001']}
					/>
					<mesh
						name='Mesh061_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_1.geometry}
						material={materials['Material #23584.001']}
					/>
					<mesh
						name='Mesh061_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_2.geometry}
						material={materials['Material #621.001']}
					/>
					<mesh
						name='Mesh061_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_3.geometry}
						material={materials['Material #20167.001']}
					/>
					<mesh
						name='Mesh061_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_4.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh061_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_5.geometry}
						material={materials['Material #8757.001']}
					/>
					<mesh
						name='Mesh061_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_6.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh061_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_7.geometry}
						material={materials['Material #10915.001']}
					/>
					<mesh
						name='Mesh061_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_8.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh061_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_9.geometry}
						material={materials['Material #6117.001']}
					/>
					<mesh
						name='Mesh061_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh061_10.geometry}
						material={materials['Material #6383.001']}
					/>
				</group>
				<group
					name='Box085'
					position={[6.227, 0.44, 6.356]}
					scale={16.371}
					userData={{
						name: 'Box085',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 658,
					}}>
					<mesh
						name='Mesh064'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh064_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_1.geometry}
						material={materials['Material #11210.001']}
					/>
					<mesh
						name='Mesh064_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_2.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh064_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_3.geometry}
						material={materials['Material #9279.001']}
					/>
					<mesh
						name='Mesh064_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_4.geometry}
						material={materials['Material #14956.001']}
					/>
					<mesh
						name='Mesh064_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_5.geometry}
						material={materials['Material #6680.001']}
					/>
					<mesh
						name='Mesh064_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_6.geometry}
						material={materials['Material #8759.001']}
					/>
					<mesh
						name='Mesh064_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_7.geometry}
						material={materials['Material #8751.001']}
					/>
					<mesh
						name='Mesh064_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_8.geometry}
						material={materials['MultiMat_13 Slot #14.001']}
					/>
					<mesh
						name='Mesh064_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_9.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh064_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_10.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh064_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_11.geometry}
						material={materials['Material #8757.001']}
					/>
					<mesh
						name='Mesh064_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_12.geometry}
						material={materials['Material #8750.001']}
					/>
					<mesh
						name='Mesh064_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_13.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh064_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_14.geometry}
						material={materials['Material #8749.001']}
					/>
					<mesh
						name='Mesh064_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_15.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh064_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_16.geometry}
						material={materials['Material #8748.001']}
					/>
					<mesh
						name='Mesh064_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_17.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh064_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_18.geometry}
						material={materials['01 - Default.001']}
					/>
					<mesh
						name='Mesh064_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_19.geometry}
						material={materials['Material #8756.001']}
					/>
					<mesh
						name='Mesh064_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_20.geometry}
						material={materials['Material #7671.001']}
					/>
					<mesh
						name='Mesh064_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_21.geometry}
						material={materials['MultiMat_13 Slot #34.001']}
					/>
					<mesh
						name='Mesh064_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_22.geometry}
						material={materials['MultiMat_13 Slot #35.001']}
					/>
					<mesh
						name='Mesh064_23'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_23.geometry}
						material={materials['MultiMat_13 Slot #36.001']}
					/>
					<mesh
						name='Mesh064_24'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_24.geometry}
						material={materials['MultiMat_13 Slot #37.001']}
					/>
					<mesh
						name='Mesh064_25'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_25.geometry}
						material={materials['MultiMat_13 Slot #38.001']}
					/>
					<mesh
						name='Mesh064_26'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_26.geometry}
						material={materials['MultiMat_13 Slot #39.001']}
					/>
					<mesh
						name='Mesh064_27'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_27.geometry}
						material={materials['MultiMat_13 Slot #40.001']}
					/>
					<mesh
						name='Mesh064_28'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_28.geometry}
						material={materials['MultiMat_13 Slot #41.001']}
					/>
					<mesh
						name='Mesh064_29'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_29.geometry}
						material={materials['MultiMat_13 Slot #42.001']}
					/>
					<mesh
						name='Mesh064_30'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_30.geometry}
						material={materials['MultiMat_13 Slot #43.001']}
					/>
					<mesh
						name='Mesh064_31'
						castShadow
						receiveShadow
						geometry={nodes.Mesh064_31.geometry}
						material={materials['MultiMat_13 Slot #44.001']}
					/>
				</group>
				<group
					name='Cylinder276'
					position={[5.59, 0.117, 10.287]}
					scale={16.371}
					userData={{
						name: 'Cylinder276',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 661,
					}}>
					<mesh
						name='Mesh067'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh067_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_1.geometry}
						material={materials['Material #560.001']}
					/>
					<mesh
						name='Mesh067_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_2.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh067_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_3.geometry}
						material={materials['Material #8425.001']}
					/>
					<mesh
						name='Mesh067_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_4.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh067_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_5.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh067_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_6.geometry}
						material={materials['Material #11539.001']}
					/>
					<mesh
						name='Mesh067_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_7.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh067_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_8.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh067_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_9.geometry}
						material={materials['Material #8757.001']}
					/>
					<mesh
						name='Mesh067_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_10.geometry}
						material={materials['Material #9307.001']}
					/>
					<mesh
						name='Mesh067_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh067_11.geometry}
						material={materials['Material #14956.001']}
					/>
				</group>
				<group
					name='Usine'
					position={[8.649, 1.535, 1.577]}
					scale={16.371}
					userData={{
						name: 'Usine',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 656,
					}}>
					<mesh
						name='Mesh062'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh062_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_1.geometry}
						material={materials['Material #6680.001']}
					/>
					<mesh
						name='Mesh062_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_2.geometry}
						material={materials['Material #10767.001']}
					/>
					<mesh
						name='Mesh062_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_3.geometry}
						material={materials['Material #10726.001']}
					/>
					<mesh
						name='Mesh062_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_4.geometry}
						material={materials['Material #10724.001']}
					/>
					<mesh
						name='Mesh062_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_5.geometry}
						material={materials['Material #10725.001']}
					/>
					<mesh
						name='Mesh062_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_6.geometry}
						material={materials['Material #8757.001']}
					/>
					<mesh
						name='Mesh062_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_7.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh062_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_8.geometry}
						material={materials['MultiMat_11 Slot #12.001']}
					/>
					<mesh
						name='Mesh062_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_9.geometry}
						material={materials['MultiMat_11 Slot #13.001']}
					/>
					<mesh
						name='Mesh062_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_10.geometry}
						material={materials['MultiMat_11 Slot #14.001']}
					/>
					<mesh
						name='Mesh062_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_11.geometry}
						material={materials['Material #8756.001']}
					/>
					<mesh
						name='Mesh062_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_12.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh062_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh062_13.geometry}
						material={materials['Material #9279.001']}
					/>
				</group>
				<group
					name='Theatre'
					position={[4.425, 3.14, -7.968]}
					scale={16.371}
					userData={{
						name: 'Theatre',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 663,
					}}>
					<mesh
						name='Mesh069'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069.geometry}
						material={materials['Material #8425.001']}
					/>
					<mesh
						name='Mesh069_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_1.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh069_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_2.geometry}
						material={materials['01 - Default.001']}
					/>
					<mesh
						name='Mesh069_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_3.geometry}
						material={materials['Material #22529.001']}
					/>
					<mesh
						name='Mesh069_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_4.geometry}
						material={materials['Material #20167.001']}
					/>
					<mesh
						name='Mesh069_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_5.geometry}
						material={materials['Material #22530.001']}
					/>
					<mesh
						name='Mesh069_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_6.geometry}
						material={materials['Material #21400.001']}
					/>
					<mesh
						name='Mesh069_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_7.geometry}
						material={materials['Material #6117.001']}
					/>
					<mesh
						name='Mesh069_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_8.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh069_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_9.geometry}
						material={materials['Material #21252.001']}
					/>
					<mesh
						name='Mesh069_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_10.geometry}
						material={materials['Material #21253.001']}
					/>
					<mesh
						name='Mesh069_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_11.geometry}
						material={materials['Material #21266.001']}
					/>
					<mesh
						name='Mesh069_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_12.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh069_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_13.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh069_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_14.geometry}
						material={materials['Material #21007.001']}
					/>
					<mesh
						name='Mesh069_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_15.geometry}
						material={materials['Material #23482.001']}
					/>
					<mesh
						name='Mesh069_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_16.geometry}
						material={materials['Material #20964.001']}
					/>
					<mesh
						name='Mesh069_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_17.geometry}
						material={materials['Material #20963.001']}
					/>
					<mesh
						name='Mesh069_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_18.geometry}
						material={materials['Material #20965.001']}
					/>
					<mesh
						name='Mesh069_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_19.geometry}
						material={materials['Material #24544.001']}
					/>
					<mesh
						name='Mesh069_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_20.geometry}
						material={materials['Material #621.001']}
					/>
					<mesh
						name='Mesh069_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_21.geometry}
						material={materials['Material #6404.001']}
					/>
					<mesh
						name='Mesh069_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_22.geometry}
						material={materials['Material #6383.001']}
					/>
					<mesh
						name='Mesh069_23'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_23.geometry}
						material={materials['Material #563.001']}
					/>
					<mesh
						name='Mesh069_24'
						castShadow
						receiveShadow
						geometry={nodes.Mesh069_24.geometry}
						material={materials['Material #560.001']}
					/>
				</group>
				<group
					name='Building_entrée_Isle_3'
					position={[-4.606, 2.969, 4.485]}
					scale={16.371}
					userData={{
						name: 'Building entrée Isle 3',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 670,
					}}>
					<mesh
						name='Mesh076'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh076_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_1.geometry}
						material={materials['Material #7009.001']}
					/>
					<mesh
						name='Mesh076_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_2.geometry}
						material={materials['MultiMat_24 Slot #41.001']}
					/>
					<mesh
						name='Mesh076_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_3.geometry}
						material={materials['MultiMat_24 Slot #46.001']}
					/>
					<mesh
						name='Mesh076_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_4.geometry}
						material={materials['Material #6680.001']}
					/>
					<mesh
						name='Mesh076_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_5.geometry}
						material={materials['MultiMat_24 Slot #67.001']}
					/>
					<mesh
						name='Mesh076_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_6.geometry}
						material={materials['MultiMat_24 Slot #87.001']}
					/>
					<mesh
						name='Mesh076_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_7.geometry}
						material={materials['MultiMat_24 Slot #89.001']}
					/>
					<mesh
						name='Mesh076_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_8.geometry}
						material={materials['MultiMat_24 Slot #91.001']}
					/>
					<mesh
						name='Mesh076_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_9.geometry}
						material={materials['Material #6133.001']}
					/>
					<mesh
						name='Mesh076_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_10.geometry}
						material={materials['MultiMat_24 Slot #112.001']}
					/>
					<mesh
						name='Mesh076_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_11.geometry}
						material={materials['MultiMat_24 Slot #113.001']}
					/>
					<mesh
						name='Mesh076_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_12.geometry}
						material={materials['MultiMat_24 Slot #115.001']}
					/>
					<mesh
						name='Mesh076_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_13.geometry}
						material={materials['MultiMat_24 Slot #116.001']}
					/>
					<mesh
						name='Mesh076_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_14.geometry}
						material={materials['MultiMat_24 Slot #137.001']}
					/>
					<mesh
						name='Mesh076_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_15.geometry}
						material={materials['MultiMat_24 Slot #138.001']}
					/>
					<mesh
						name='Mesh076_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_16.geometry}
						material={materials['MultiMat_24 Slot #139.001']}
					/>
					<mesh
						name='Mesh076_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_17.geometry}
						material={materials['MultiMat_24 Slot #140.001']}
					/>
					<mesh
						name='Mesh076_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_18.geometry}
						material={materials['MultiMat_24 Slot #141.001']}
					/>
					<mesh
						name='Mesh076_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_19.geometry}
						material={materials['MultiMat_24 Slot #142.001']}
					/>
					<mesh
						name='Mesh076_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_20.geometry}
						material={materials['MultiMat_24 Slot #143.001']}
					/>
					<mesh
						name='Mesh076_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_21.geometry}
						material={materials['MultiMat_24 Slot #183.001']}
					/>
					<mesh
						name='Mesh076_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_22.geometry}
						material={materials['MultiMat_24 Slot #188.001']}
					/>
					<mesh
						name='Mesh076_23'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_23.geometry}
						material={materials['MultiMat_24 Slot #210.001']}
					/>
					<mesh
						name='Mesh076_24'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_24.geometry}
						material={materials['MultiMat_24 Slot #211.001']}
					/>
					<mesh
						name='Mesh076_25'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_25.geometry}
						material={materials['Material #2518.001']}
					/>
					<mesh
						name='Mesh076_26'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_26.geometry}
						material={materials['MultiMat_24 Slot #256.001']}
					/>
					<mesh
						name='Mesh076_27'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_27.geometry}
						material={materials['MultiMat_24 Slot #258.001']}
					/>
					<mesh
						name='Mesh076_28'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_28.geometry}
						material={materials['MultiMat_24 Slot #259.001']}
					/>
					<mesh
						name='Mesh076_29'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_29.geometry}
						material={materials['MultiMat_24 Slot #260.001']}
					/>
					<mesh
						name='Mesh076_30'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_30.geometry}
						material={materials['MultiMat_24 Slot #261.001']}
					/>
					<mesh
						name='Mesh076_31'
						castShadow
						receiveShadow
						geometry={nodes.Mesh076_31.geometry}
						material={materials['MultiMat_24 Slot #262.001']}
					/>
				</group>
				<group
					name='Line185'
					position={[-2.972, 0.051, 7.871]}
					scale={16.371}
					userData={{
						name: 'Line185',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 669,
					}}>
					<mesh
						name='Mesh075'
						castShadow
						receiveShadow
						geometry={nodes.Mesh075.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh075_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh075_1.geometry}
						material={materials['Material #9278.001']}
					/>
					<mesh
						name='Mesh075_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh075_2.geometry}
						material={materials['Material #6680.001']}
					/>
				</group>
				<group
					name='Junk_Yard'
					position={[-5.023, 2.832, -6.001]}
					scale={16.371}
					userData={{
						name: 'Junk Yard',
						'MapChannel:1': 'UVChannel_1',
						MaxHandle: 672,
					}}>
					<mesh
						name='Mesh078'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078.geometry}
						material={materials['Material #8759.001']}
					/>
					<mesh
						name='Mesh078_1'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_1.geometry}
						material={materials['Material #7673.001']}
					/>
					<mesh
						name='Mesh078_2'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_2.geometry}
						material={materials['Material #17533.001']}
					/>
					<mesh
						name='Mesh078_3'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_3.geometry}
						material={materials['Material #17695.001']}
					/>
					<mesh
						name='Mesh078_4'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_4.geometry}
						material={materials['Material #9130.001']}
					/>
					<mesh
						name='Mesh078_5'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_5.geometry}
						material={materials['Material #7671.001']}
					/>
					<mesh
						name='Mesh078_6'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_6.geometry}
						material={materials['Material #621.001']}
					/>
					<mesh
						name='Mesh078_7'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_7.geometry}
						material={materials['Material #23442.001']}
					/>
					<mesh
						name='Mesh078_8'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_8.geometry}
						material={materials['Material #16949.001']}
					/>
					<mesh
						name='Mesh078_9'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_9.geometry}
						material={materials['Material #16634.001']}
					/>
					<mesh
						name='Mesh078_10'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_10.geometry}
						material={materials['MultiMat_26 Slot #20.001']}
					/>
					<mesh
						name='Mesh078_11'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_11.geometry}
						material={materials['Material #16461.001']}
					/>
					<mesh
						name='Mesh078_12'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_12.geometry}
						material={materials['Material #16462.001']}
					/>
					<mesh
						name='Mesh078_13'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_13.geometry}
						material={materials['Material #16488.001']}
					/>
					<mesh
						name='Mesh078_14'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_14.geometry}
						material={materials['Material #3568.001']}
					/>
					<mesh
						name='Mesh078_15'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_15.geometry}
						material={materials['Material #16503.001']}
					/>
					<mesh
						name='Mesh078_16'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_16.geometry}
						material={materials['Material #2279.001']}
					/>
					<mesh
						name='Mesh078_17'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_17.geometry}
						material={materials['Material #6342.001']}
					/>
					<mesh
						name='Mesh078_18'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_18.geometry}
						material={materials['Material #23584.001']}
					/>
					<mesh
						name='Mesh078_19'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_19.geometry}
						material={materials['Material #16069.001']}
					/>
					<mesh
						name='Mesh078_20'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_20.geometry}
						material={materials['Material #15819.001']}
					/>
					<mesh
						name='Mesh078_21'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_21.geometry}
						material={materials['Material #6383.001']}
					/>
					<mesh
						name='Mesh078_22'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_22.geometry}
						material={materials['Material #6421.001']}
					/>
					<mesh
						name='Mesh078_23'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_23.geometry}
						material={materials['Material #15618.001']}
					/>
					<mesh
						name='Mesh078_24'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_24.geometry}
						material={materials['Material #14956.001']}
					/>
					<mesh
						name='Mesh078_25'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_25.geometry}
						material={materials['Material #10445.001']}
					/>
					<mesh
						name='Mesh078_26'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_26.geometry}
						material={materials['Material #9279.001']}
					/>
					<mesh
						name='Mesh078_27'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_27.geometry}
						material={materials['Material #14827.001']}
					/>
					<mesh
						name='Mesh078_28'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_28.geometry}
						material={materials['MultiMat_26 Slot #66.001']}
					/>
					<mesh
						name='Mesh078_29'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_29.geometry}
						material={materials['MultiMat_26 Slot #67.001']}
					/>
					<mesh
						name='Mesh078_30'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_30.geometry}
						material={materials['MultiMat_26 Slot #68.001']}
					/>
					<mesh
						name='Mesh078_31'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_31.geometry}
						material={materials['MultiMat_26 Slot #69.001']}
					/>
					<mesh
						name='Mesh078_32'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_32.geometry}
						material={materials['MultiMat_26 Slot #70.001']}
					/>
					<mesh
						name='Mesh078_33'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_33.geometry}
						material={materials['MultiMat_26 Slot #71.001']}
					/>
					<mesh
						name='Mesh078_34'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_34.geometry}
						material={materials['MultiMat_26 Slot #72.001']}
					/>
					<mesh
						name='Mesh078_35'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_35.geometry}
						material={materials['MultiMat_26 Slot #73.001']}
					/>
					<mesh
						name='Mesh078_36'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_36.geometry}
						material={materials['MultiMat_26 Slot #74.001']}
					/>
					<mesh
						name='Mesh078_37'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_37.geometry}
						material={materials['MultiMat_26 Slot #75.001']}
					/>
					<mesh
						name='Mesh078_38'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_38.geometry}
						material={materials['MultiMat_26 Slot #76.001']}
					/>
					<mesh
						name='Mesh078_39'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_39.geometry}
						material={materials['MultiMat_26 Slot #77.001']}
					/>
					<mesh
						name='Mesh078_40'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_40.geometry}
						material={materials['MultiMat_26 Slot #78.001']}
					/>
					<mesh
						name='Mesh078_41'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_41.geometry}
						material={materials['MultiMat_26 Slot #79.001']}
					/>
					<mesh
						name='Mesh078_42'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_42.geometry}
						material={materials['MultiMat_26 Slot #80.001']}
					/>
					<mesh
						name='Mesh078_43'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_43.geometry}
						material={materials['MultiMat_26 Slot #81.001']}
					/>
					<mesh
						name='Mesh078_44'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_44.geometry}
						material={materials['MultiMat_26 Slot #82.001']}
					/>
					<mesh
						name='Mesh078_45'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_45.geometry}
						material={materials['MultiMat_26 Slot #83.001']}
					/>
					<mesh
						name='Mesh078_46'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_46.geometry}
						material={materials['MultiMat_26 Slot #84.001']}
					/>
					<mesh
						name='Mesh078_47'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_47.geometry}
						material={materials['MultiMat_26 Slot #85.001']}
					/>
					<mesh
						name='Mesh078_48'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_48.geometry}
						material={materials['MultiMat_26 Slot #86.001']}
					/>
					<mesh
						name='Mesh078_49'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_49.geometry}
						material={materials['MultiMat_26 Slot #87.001']}
					/>
					<mesh
						name='Mesh078_50'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_50.geometry}
						material={materials['MultiMat_26 Slot #88.001']}
					/>
					<mesh
						name='Mesh078_51'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_51.geometry}
						material={materials['MultiMat_26 Slot #89.001']}
					/>
					<mesh
						name='Mesh078_52'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_52.geometry}
						material={materials['MultiMat_26 Slot #90.001']}
					/>
					<mesh
						name='Mesh078_53'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_53.geometry}
						material={materials['MultiMat_26 Slot #91.001']}
					/>
					<mesh
						name='Mesh078_54'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_54.geometry}
						material={materials['MultiMat_26 Slot #92.001']}
					/>
					<mesh
						name='Mesh078_55'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_55.geometry}
						material={materials['MultiMat_26 Slot #93.001']}
					/>
					<mesh
						name='Mesh078_56'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_56.geometry}
						material={materials['MultiMat_26 Slot #94.001']}
					/>
					<mesh
						name='Mesh078_57'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_57.geometry}
						material={materials['MultiMat_26 Slot #95.001']}
					/>
					<mesh
						name='Mesh078_58'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_58.geometry}
						material={materials['MultiMat_26 Slot #96.001']}
					/>
					<mesh
						name='Mesh078_59'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_59.geometry}
						material={materials['MultiMat_26 Slot #97.001']}
					/>
					<mesh
						name='Mesh078_60'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_60.geometry}
						material={materials['MultiMat_26 Slot #98.001']}
					/>
					<mesh
						name='Mesh078_61'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_61.geometry}
						material={materials['MultiMat_26 Slot #99.001']}
					/>
					<mesh
						name='Mesh078_62'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_62.geometry}
						material={materials['MultiMat_26 Slot #100.001']}
					/>
					<mesh
						name='Mesh078_63'
						castShadow
						receiveShadow
						geometry={nodes.Mesh078_63.geometry}
						material={materials['MultiMat_26 Slot #101.001']}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/myHolo.gltf');
